# Generated by Django 4.2.10 on 2024-02-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poster', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/cc')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_and_time', models.DateTimeField()),
                ('ticket_link', models.URLField()),
                ('image', models.ImageField(upload_to='images/e')),
                ('going', models.BooleanField(default=False)),
                ('cultural_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myartapp.culturalcenter')),
            ],
        ),
    ]
